version: '3'

services:

    sda-test-app:
        image: scaleit/sda-test-app:demo1.0.0
        build: ./Domain Software/Test App
        # no port declaration because the app should be isolated
            
    x-spsc-identity-mananger:
        image: scaleit/spsc-identity-manager:demo1.0.0
        build: ./Platform Sidecars/Identity-Manager
 
    x-spsc-license-mananger:
        image: scaleit/spsc-license-manager:demo1.0.0
        build: ./Platform Sidecars/License-Manager

    x-spsc-router:
        image: scaleit/spsc-router:demo1.0.0
        build: ./Platform Sidecars/Router
        expose:
            - 1000
        environment:
            - VIRTUAL_HOST=sidecar.app.staging.teco.edu
            - VIRTUAL_PORT=1000
        networks:
            - default
            - nginx-proxy

networks:
    nginx-proxy:
        external: true
